#!/bin/bash

function install()
{
    cd $1
    /home/zanzes/.virtualenvs/lztools/bin/python3.7 setup.py install
    rm -rf dist/
    rm -rf build/
    rm -rf *.egg-info/
    cd ..
}



dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
for f in $(ls $dir)
do
    if [[ -d $f ]]; then
	    install $f
    fi
done
