#!/bin/bash

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

workon lztools
eval "$(_LZTOOLS_COMPLETE=source lztools)"
