#!  /usr/bin/env python
# -*- coding: utf-8 -*-

import argparse, re

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("EXPR", type=str, default=None, help="Your regex pattern")
parser.add_argument("TEXT", type=str, default=None, help="The text to search for 'EXPR'")
grp = parser.add_mutually_exclusive_group(required=False)
grp.add_argument("-f", "--FirstOnly", action='store_true', default=False, help="Finish searching on first result")
grp.add_argument("-a", "--All", action='store_true', default=True, help="Return all results")

args = parser.parse_args()

if args.All:
    for x in re.findall(args.EXPR, args.TEXT):
        print(x)
elif args.FirstOnly:
    print re.search(args.EXPR, args.TEXT).group(0)

