#!/bin/bash

original=$(pwd)
rfile=$(realpath "$0")
rdir=$(dirname $rfile)
cd $rdir

args=""

if [[ $1 == "-f" || $2 == "-f" ]]; then
    args="-f"
fi

for x in $(ls $rdir);do
    if [[ $x != *.* ]]; then
        rp=$(realpath $x)
        if [[ $rp != $rfile && "$(dirname $rp)/__init__.py" != $rfile ]]; then
            $rdir/link-command $x $args
        fi
    fi
done

cd $original