#!  /usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import re

from PowerUtils.PowerDev import install_module

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("Path", type=str, default=None, help="Path to module")
parser.add_argument("-u", "--upload", type=str, default=None, help="Upload module to PyPy")

args = parser.parse_args()

install_module(args.Path)

