#!  /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import os

p = argparse.ArgumentParser()
p.add_argument("Name", type=str, help="Name of the pip module")

args = p.parse_args()
e = "tmp"
if args.output is not None:
    e = args.output
os.system('mdecrypt {} {} {}'.format(args.passwd, args.file, e))