#!  /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse

from PowerUtils.Modules import get_version_online

p = argparse.ArgumentParser()
p.add_argument("Name", type=str, help="Name of the pip module")

args = p.parse_args()

print get_version_online(args.Name)