#!/bin/bash

args="-v"
file=""

if [[ $1 != "-f" ]]; then
    # echo "Warning: overriding existing files"
    #
    file=$1
    if [[ $2 == "-f" ]]; then
        args="$args -f"
    fi
else
    file=$2
    args="$args -f"
fi

sudo ln $args $file /usr/bin/$(basename $file)