#!/bin/bash

original=$(pwd)
rfile=$(realpath "$0")
rdir=$(dirname $rfile)
cd $rdir

args=""

if [[ $1 == "-f" || $2 == "-f" ]]; then
    args="-f"
fi

for x in $(ls $rdir);doyes
    if [[ $(realpath $x) != $rfile ]]; then
        $rdir/link-command $x $args
    fi
done

cd $original