#!  /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import os

p = argparse.ArgumentParser()
p.add_argument("passwd", type=str, help="Password")
p.add_argument("file", type=str, help="File to decrypt")
p.add_argument("-o","--output", type=str, help="Output directory", default=None, const=None, required=False)

args = p.parse_args()
e = "tmp"
if args.output is not None:
    e = args.output
os.system('mdecrypt {} {} {}'.format(args.passwd, args.file, e))