#!  /usr/bin/env python3.7
# -*- coding: utf-8 -*-

import argparse
import re

from lztools.Modules import local_install

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("Path", type=str, default=None, help="Path to module")
parser.add_argument("-u", "--upload", action='store_true', default=False, help="Upload module to PyPy")

args = parser.parse_args()

local_install(args.Path, upload=args.upload)

