#!  /usr/bin/env python3.7
# -*- coding: utf-8 -*-

import argparse
import re

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("ITEM", type=str, default="", help="The item to search for")
parser.add_argument("LIST", type=str, default="", help="The list to search", nargs="*")

args = parser.parse_args()

try:
    if args.ITEM in args.LIST:
        print(args.ITEM)

except:
    pass

