#!  /usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import re

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("ITEM", type=str, default="", help="The item to search for")
parser.add_argument("LIST", type=str, default="", help="The list to search")

args = parser.parse_args()


print("Item: {}".format(args.ITEM))
print("List: 1 {} 2".format(args.LIST))



