#!  /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import hashlib
import os
import struct

from Crypto.Cipher import AES

p = argparse.ArgumentParser()
p.add_argument("passwd", type=str, help="Password")
p.add_argument("file", type=str, help="File to decrypt")
args = p.parse_args()


def decrypt_file(passwd, in_filename, out_filename=None, chunksize=24*1024):

    key = hashlib.sha256(passwd).digest()

    if not out_filename:
        out_filename = os.path.splitext(in_filename)[0]

    with open(in_filename, 'rb') as infile:
        # decryptor = AES.new(key, AES.MODE_CBC, iv)
        decryptor = AES.new(key)

        with open(out_filename, 'wb') as outfile:
            chunk = infile.read()

            outfile.write(decryptor.decrypt(chunk))

decrypt_file(args.passwd, args.file)