#!  /usr/bin/env python3.7
# -*- coding: utf-8 -*-
import argparse
import subprocess
import re

p = argparse.ArgumentParser()
p.add_argument("-a", "--all", action="store_true", help="Kill all even attached tmux sessions", default=False, required=False)
args = p.parse_args()

strs = subprocess.check_output(["tmux", "list-s"]).split("\n")[:-1]

ps = []

for x in (re.search("\d+:", x).group(0)[:-1] for x in strs if args.all or (not args.all and not x.endswith("(attached)"))):
    subprocess.call(["tmux", "kill-ses", "-t", x])